config/routes.rb
Rails.application.routes.draw do
  resources :tournaments
  resources :players
  resources :articles
  resources :s3_uploads
  devise_for :users
  resources :search, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home_page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many_attached :images

  def self.order_by_date
    all.order("date desc")
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :players

  has_one_attached :flag
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :country, optional: true
  belongs_to :tennis_association, optional: true

  has_one :team, dependent: :destroy
  has_one :size, dependent: :destroy
  has_one :earnings, dependent: :destroy
  has_one :playing_style, dependent: :destroy
  has_one :bio, dependent: :destroy
  has_one :singles_stats, dependent: :destroy
  has_many :singles_matches, ->(player) { 
    unscope(where: :player_id).where("player_1_id = ? OR player_2_id = ?", player.id, player.id)
  }, dependent: :destroy
  has_one :doubles_stats, dependent: :destroy
  has_one_attached :headshot

  def overview
    {
      name: "#{first_name} #{last_name}",
      country: country&.name,
      singles_ranking: singles_stats&.ranking,
      singles_points: singles_stats&.points,
      singles_titles: singles_stats&.career_titles,
      singles_record: singles_stats&.career_record,
      doubles_ranking: doubles_stats&.ranking,
      doubles_points: doubles_stats&.points,
      doubles_titles: doubles_stats&.career_titles,
      doubles_record: doubles_stats.career_record,
      racquet_hand: playing_style&.racquet_hand,
      backhand: playing_style&.backhand,
      height: size&.height,
      weight: size&.weight,
      earnings: earnings&.prize_money,
      coach: team&.compact_coach,
      residence: bio&.residence
    }
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/player_models/bio.rb
class Bio < ApplicationRecord
  belongs_to :player
end

app/models/player_models/size.rb
class Size < ApplicationRecord
  belongs_to :player

  def height_to_cm
    "#{height} cm"
  end

  def weight_to_kilos
    "#{weight} kg"
  end
end

app/models/player_models/team.rb
class Team < ApplicationRecord
  serialize :coach

  belongs_to :player

  def compact_coach
    coach.length == 1 ? coach.first : coach
  end
end

app/models/tennis_association.rb
class TennisAssociation < ApplicationRecord

  has_many :players

  private

  def self.atp
    find_by(acronym: "ATP")
  end

  def self.wta
    find_by(acronym: "WTA")
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :singles_matches, dependent: :destroy

  has_one_attached :image

  def self.order_by_start_date
    all.order("start_date desc")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @pagy, @articles = pagy(Article.order_by_date, items: 10)
  end

  def show
    @article = Article.find_by_id(params[:id])
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @articles = Article.order_by_date
    @recent_matches = SinglesMatch.order_by_date
    @atp_players = TennisAssociation.atp&.players
    @wta_players = TennisAssociation.wta&.players
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @pagy, @atp_players = pagy(TennisAssociation.atp.players, items: 10)
    @pagy, @wta_players = pagy(TennisAssociation.wta.players, items: 10)
  end

  def show
    @player = Player.find_by_id(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    entry = params[:entry].downcase
    @search_facade = SearchFacade.new(entry)
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @pagy, @tournaments = pagy(Tournament.order_by_start_date, items: 10)
  end

  def show
    @tournament = Tournament.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/home_page/_headlines.html.slim
h3.headline_section_title.mt-4 More Headlines

- @articles.drop(4).each do |article|
  = render "articles/headline_card", article: article

app/views/home_page/_news_images.html.slim
.row
  .col-6.main_news_image.pl-0
    = image_tag @articles.first.images.first.variant(resize: "600x600"), class: "h-100"
    = link_to @articles.first.title, article_path(@articles.first.id), class: "main-caption-overlay"
  .col-2
    .row
      - @articles[1..3].each do |article|
        .col.side_news_image.px-0
          = image_tag article.images.first.variant(resize: "250x250"), class: "h-100"
          = link_to article.title, article_path(article.id), class: "side-caption-overlay"
        .w-100
  .col-4.bg-white
    h5.text-center.mt-2 Recent Matches
    = render "home_page/recent_matches"

app/views/home_page/_player_carousel.html.slim
div[id=carousel_id class="carousel slide"]
  div[class="carousel-inner clickable_with_tint"]
    - players&.each_with_index do |player, index|
      div[
        class=(index == 0 ? "carousel-item active" : "carousel-item")
        style="background: linear-gradient(rgba(255,255,255,.5), rgba(255,255,255,.5)), url(#{url_for(player.country.flag)});"
      ]
        .d-flex onclick="redirect_player_show(#{player.id})"
          = image_tag player.headshot.variant(resize: "300x300"), class: "w-75"
          div.text-right.text-white.w-25.pr-3.text-outline
            h1 = "##{player.singles_stats.ranking}"
            h3 = player.last_name
  a[class="carousel-control-prev" href="##{carousel_id}" role="button" data-slide="prev"]
    span[class="carousel-control-prev-icon" aria-hidden="true"]
    span[class="sr-only"]Previous
  a[class="carousel-control-next" href="##{carousel_id}" role="button" data-slide="next"]
    span[class="carousel-control-next-icon" aria-hidden="true"]
    span[class="sr-only"]Next

javascript:
  function redirect_player_show(id) {
    window.location.href = "/players/" + id
  }

app/views/home_page/_player_match_grid.html.slim
- winner = match.winner_id == player.id
.col.border.border-dark
  = image_tag player.country.flag.variant(resize: "15x15")
  .d-inline.ml-3.mr-2 = player.singles_stats.ranking
  = player.last_name
  - if winner
    i.bi.bi-check.text-success
- match.sets.each do |set|
  .col-1.border.border-dark
    - won_set = set[position] == set.max
    div class=("font-weight-bold" if won_set) 
      = set[position]

app/views/home_page/_ranking_images.html.slim
.row.mt-5
  .col
    = render "player_carousel", players: @atp_players, carousel_id: "mensCarousel"
  .col
    = render "player_carousel", players: @wta_players, carousel_id: "womensCarousel"

app/views/home_page/_recent_matches.html.slim
- @recent_matches.each do |match|
  .row.mx-2.my-4.bg-white
    .col.border.border-dark.text-center.bg-secondary.text-white
      = "#{match.tournament.name} - #{match.round.capitalize} - #{match.gender}"
    .w-100
    .col
      = render "tournaments/match_grid_row", match: match, player: match.player_1, position: 0
      = render "tournaments/match_grid_row", match: match, player: match.player_2, position: 1

app/views/home_page/index.html.slim
= render "news_images"
= render "headlines"
= render "ranking_images"

app/views/search/index.html.slim
- if @search_facade.player_results.present?
  h2.my-4 Players
  .pb-3
    - @search_facade.player_results.each do |player|
      .w-50
        = render "players/player_card", player: player

- if @search_facade.article_results.present?
  h2.mt-3.mb-4 Articles
  - @search_facade.article_results.each do |article|
    = render "articles/headline_card", article: article

- if @search_facade.tournament_results.present?
  h2.mt-3.mb-4 Tournaments
  = render "tournaments/tournament_cards", tournaments: @search_facade.tournament_results

- if @search_facade.singles_matches_results.present?
  h2.mt-3.mb-4 Singles Matches
  .row
    - @search_facade.singles_matches_results.each_with_index do |match, index|
      .col-4
        .row.mx-2.my-4.bg-white
          .col.border.border-dark.text-center.bg-secondary.text-white
            = "#{match.tournament.name} - #{match.round.capitalize}"
          .w-100
          .col
            = render "tournaments/match_grid_row", match: match, player: match.player_1, position: 0
            = render "tournaments/match_grid_row", match: match, player: match.player_2, position: 1

- if @search_facade.no_results?
  h4.mt-5.text-center Sorry, no results were found! Try re-wording your search.